#!/usr/bin/env ruby

# check binding.pry
cached_files = `git diff --cached --name-only`
if cached_files.split($/).all? { |path| File.read(path).include?('binding.pry') }
  puts 'WARNING: binding.pry is found.'
  exit 1
end
